name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  analyze:
    name: Build & Test
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run your existing setup script
      - name: Run setup.sh
        run: |
          chmod +x ./setup.sh
          sudo ./setup.sh -y

      # Build the project
      - name: Build project
        run: make all

      # Run unit tests with Valgrind
      - name: Run tests with Valgrind
        run: make valgrind
