name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  analyze:
    name: Build & Test
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make setup.sh executable
        run: chmod +x ./setup.sh

      - name: Run setup.sh with auto-yes
        run: ./setup.sh -y

      - name: Build project
        run: make all

      - name: Run unit tests with Valgrind
        run: make valgrind
